services:
  fastapi:
    build: .
    container_name: pdf_rag_api
    command: bash -c "apt-get update && apt-get install -y curl && uvicorn app.app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
    environment:
      QDRANT_URL: "http://qdrant:6333"
      REDIS_URL: "redis://redis:6379/0"
      PYTHONPATH: /code
    env_file:
      - .env
    working_dir: /code
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.9.0
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: celery_worker
    command: celery -A workers.celery_worker.celery_app worker --loglevel=INFO
    depends_on:
      fastapi:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
    environment:
      QDRANT_URL: "http://qdrant:6333"
      REDIS_URL: "redis://redis:6379/0"
      PYTHONPATH: /code
    env_file:
      - .env
    working_dir: /code

  streamlit:
    build: .
    container_name: cerebralzip_streamlit
    command: sh -c "sleep 15 && streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      fastapi:
        condition: service_healthy
    environment:
      API_URL: "http://fastapi:8000"
      PYTHONPATH: /code
    working_dir: /code